name: Build Engine

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      # Buraya "Build Engine" oluşturmak için gereken adımları ekleyin

